### ISSUE TITLE
fatal error when trying to add a new sector/area of expertise to a contact

### ISSUE THREAD

**Issue by jaapjansma** [CiviCooP/org.civicoop.contactsegment#3]
I have setup one sector (Retail) and one area of expertise (Inkoop) and I wanted to link from my contact card. So I went to my contact card, clicked on Sector and areas of expertise and then add sector or area of expertise. I then get a fatal error and I am not able to add a sector or area of expertise to my contact card

![screenshot from 2015-12-21 20-05-56](https://cloud.githubusercontent.com/assets/4126292/11938949/a311cb54-a81e-11e5-8b42-7d8b0c6b8ca7.png)

**Comment by ErikHommel** [comment]
Could not replicate in current versions

**Comment by jaapjansma** [comment]
I have installed the latest version and the fatal error disappeared.

**Comment by ErikHommel** [comment]
top, opgelost :-)
